# CMPE 255 Assignment 1 — Part 2
## Experiment 00: Dynamic Todo Workspace

### AI-Assisted Replication of Instructor Project 00

This notebook implements a compact version of the Dynamic Todo Workspace project from the instructor's `data_science_examples` repository.

The original project focuses on building an interactive task management application with a modern user interface.

For this assignment, I created a lightweight version using Python and Gradio.

### Main Features

- Add a new task
- View current tasks
- Mark a task as completed
- Delete a task
- Track task status
- Interactive web interface

### Adaptation

Instead of building a large full-stack application, this experiment focuses on the core goal of the project: creating a working and interactive task management workspace.

In [1]:
!pip -q install gradio

In [2]:
import gradio as gr
import pandas as pd

print("Libraries imported successfully.")

Libraries imported successfully.

## Application Design

The application stores tasks in a simple Python list.

Each task contains:

- Task ID
- Task description
- Status

A task can have one of two statuses:

- Pending
- Completed

The user interface communicates with Python functions that update the task list.

In [3]:
tasks = []

next_task_id = 1

print("Task workspace initialized.")

Task workspace initialized.

In [4]:
def get_task_table():

    if len(tasks) == 0:
        return pd.DataFrame(
            columns=[
                "Task ID",
                "Task",
                "Status"
            ]
        )

    return pd.DataFrame(tasks)

In [5]:
def add_task(task_text):

    global next_task_id

    task_text = task_text.strip()

    if task_text == "":
        return (
            get_task_table(),
            "Please enter a task."
        )

    new_task = {
        "Task ID": next_task_id,
        "Task": task_text,
        "Status": "Pending"
    }

    tasks.append(new_task)

    next_task_id += 1

    return (
        get_task_table(),
        "Task added successfully."
    )

In [6]:
def complete_task(task_id):

    try:
        task_id = int(task_id)

    except:
        return (
            get_task_table(),
            "Please enter a valid Task ID."
        )

    for task in tasks:

        if task["Task ID"] == task_id:

            task["Status"] = "Completed"

            return (
                get_task_table(),
                f"Task {task_id} completed."
            )

    return (
        get_task_table(),
        "Task ID not found."
    )

In [7]:
def delete_task(task_id):

    try:
        task_id = int(task_id)

    except:
        return (
            get_task_table(),
            "Please enter a valid Task ID."
        )

    for task in tasks:

        if task["Task ID"] == task_id:

            tasks.remove(task)

            return (
                get_task_table(),
                f"Task {task_id} deleted."
            )

    return (
        get_task_table(),
        "Task ID not found."
    )

In [8]:
add_task("Finish CMPE 255 assignment")
add_task("Review data science notebooks")
add_task("Record YouTube walkthrough")

get_task_table()

   Task ID                           Task   Status
0        1     Finish CMPE 255 assignment  Pending
1        2  Review data science notebooks  Pending
2        3     Record YouTube walkthrough  Pending

In [9]:
complete_task(2)

get_task_table()

   Task ID                           Task     Status
0        1     Finish CMPE 255 assignment    Pending
1        2  Review data science notebooks  Completed
2        3     Record YouTube walkthrough    Pending

## Interactive Todo Workspace

The following Gradio interface provides an interactive web interface for the task management functions.

Users can add tasks, mark tasks as completed, delete tasks, and view the current workspace.

In [11]:
with gr.Blocks(title="Dynamic Todo Workspace") as demo:

    gr.Markdown(
        """
        # Dynamic Todo Workspace

        A simple interactive task management application.

        Add tasks, complete tasks, and remove tasks from the workspace.
        """
    )

    task_table = gr.Dataframe(
        value=get_task_table(),
        headers=[
            "Task ID",
            "Task",
            "Status"
        ],
        interactive=False,
        label="Current Tasks"
    )

    status_message = gr.Textbox(
        label="Status",
        interactive=False
    )

    gr.Markdown("## Add a Task")

    task_input = gr.Textbox(
        label="Task Description",
        placeholder="Enter a new task..."
    )

    add_button = gr.Button(
        "Add Task"
    )

    gr.Markdown("## Manage a Task")

    task_id_input = gr.Number(
        label="Task ID",
        precision=0
    )

    with gr.Row():

        complete_button = gr.Button(
            "Complete Task"
        )

        delete_button = gr.Button(
            "Delete Task"
        )

    add_button.click(
        fn=add_task,
        inputs=task_input,
        outputs=[
            task_table,
            status_message
        ]
    )

    complete_button.click(
        fn=complete_task,
        inputs=task_id_input,
        outputs=[
            task_table,
            status_message
        ]
    )

    delete_button.click(
        fn=delete_task,
        inputs=task_id_input,
        outputs=[
            task_table,
            status_message
        ]
    )

demo.launch()

It looks like you are running Gradio on a hosted Jupyter notebook, which requires `share=True`. Automatically setting `share=True` (you can turn this off by setting `share=False` in `launch()` explicitly).

Colab notebook detected. To show errors in colab notebook, set debug=True in launch()
* Running on public URL: https://b09c4d7964703794e9.gradio.live

This share link is temporary and will last for up to 1 week (best effort). For free permanent hosting and GPU upgrades, run `gradio deploy` from the terminal in the working directory to deploy to Hugging Face Spaces (https://huggingface.co/spaces)

## Results

The compact Dynamic Todo Workspace successfully supports the main task management operations:

- Creating new tasks
- Displaying the current task list
- Updating a task from Pending to Completed
- Deleting existing tasks
- Providing status messages after user actions

The experiment demonstrates how a simple Python backend can be connected to an interactive web interface.

The application was tested directly through the Gradio interface to verify that the main user actions work correctly.

## Limitations

This project is a lightweight adaptation of the original Dynamic Todo Workspace concept.

The application stores tasks only in memory, so the task list is reset when the notebook runtime is restarted.

A production version could include:

- Persistent database storage
- User accounts
- Due dates
- Task priorities
- Search and filtering
- Multiple workspaces
- More advanced user interface design

For this assignment, the implementation focuses on demonstrating the core interactive task management workflow.

## Conclusion

This experiment implemented a compact Dynamic Todo Workspace using Python and Gradio.

The application allows users to:

- Add tasks
- View tasks
- Complete tasks
- Delete tasks

The project demonstrates the basic connection between application logic and an interactive user interface.

Although the implementation is smaller than a production task management system, it reproduces the core goal of creating a working dynamic todo workspace.